//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushmoLevelEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushmoLevelEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap barcode2d {
            get {
                object obj = ResourceManager.GetObject("barcode2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bin_closed {
            get {
                object obj = ResourceManager.GetObject("bin_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_0 {
            get {
                object obj = ResourceManager.GetObject("cheek_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_1 {
            get {
                object obj = ResourceManager.GetObject("cheek_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_2 {
            get {
                object obj = ResourceManager.GetObject("cheek_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_3 {
            get {
                object obj = ResourceManager.GetObject("cheek_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_4 {
            get {
                object obj = ResourceManager.GetObject("cheek_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_5 {
            get {
                object obj = ResourceManager.GetObject("cheek_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_6 {
            get {
                object obj = ResourceManager.GetObject("cheek_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cheek_7 {
            get {
                object obj = ResourceManager.GetObject("cheek_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap door_in {
            get {
                object obj = ResourceManager.GetObject("door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_0 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_1 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_2 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_3 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_4 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_5 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_6 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eye_brow_7 {
            get {
                object obj = ResourceManager.GetObject("eye_brow_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_00 {
            get {
                object obj = ResourceManager.GetObject("eyes_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_01 {
            get {
                object obj = ResourceManager.GetObject("eyes_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_02 {
            get {
                object obj = ResourceManager.GetObject("eyes_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_03 {
            get {
                object obj = ResourceManager.GetObject("eyes_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_04 {
            get {
                object obj = ResourceManager.GetObject("eyes_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_05 {
            get {
                object obj = ResourceManager.GetObject("eyes_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_06 {
            get {
                object obj = ResourceManager.GetObject("eyes_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_07 {
            get {
                object obj = ResourceManager.GetObject("eyes_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_08 {
            get {
                object obj = ResourceManager.GetObject("eyes_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_09 {
            get {
                object obj = ResourceManager.GetObject("eyes_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0A {
            get {
                object obj = ResourceManager.GetObject("eyes_0A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0B {
            get {
                object obj = ResourceManager.GetObject("eyes_0B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0C {
            get {
                object obj = ResourceManager.GetObject("eyes_0C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0D {
            get {
                object obj = ResourceManager.GetObject("eyes_0D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0E {
            get {
                object obj = ResourceManager.GetObject("eyes_0E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_0F {
            get {
                object obj = ResourceManager.GetObject("eyes_0F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_10 {
            get {
                object obj = ResourceManager.GetObject("eyes_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_11 {
            get {
                object obj = ResourceManager.GetObject("eyes_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_12 {
            get {
                object obj = ResourceManager.GetObject("eyes_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_13 {
            get {
                object obj = ResourceManager.GetObject("eyes_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_14 {
            get {
                object obj = ResourceManager.GetObject("eyes_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_15 {
            get {
                object obj = ResourceManager.GetObject("eyes_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_16 {
            get {
                object obj = ResourceManager.GetObject("eyes_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_17 {
            get {
                object obj = ResourceManager.GetObject("eyes_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_18 {
            get {
                object obj = ResourceManager.GetObject("eyes_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_19 {
            get {
                object obj = ResourceManager.GetObject("eyes_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1A {
            get {
                object obj = ResourceManager.GetObject("eyes_1A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1B {
            get {
                object obj = ResourceManager.GetObject("eyes_1B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1C {
            get {
                object obj = ResourceManager.GetObject("eyes_1C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1D {
            get {
                object obj = ResourceManager.GetObject("eyes_1D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1E {
            get {
                object obj = ResourceManager.GetObject("eyes_1E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eyes_1F {
            get {
                object obj = ResourceManager.GetObject("eyes_1F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_0 {
            get {
                object obj = ResourceManager.GetObject("face_color_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_1 {
            get {
                object obj = ResourceManager.GetObject("face_color_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_2 {
            get {
                object obj = ResourceManager.GetObject("face_color_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_3 {
            get {
                object obj = ResourceManager.GetObject("face_color_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_4 {
            get {
                object obj = ResourceManager.GetObject("face_color_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_color_5 {
            get {
                object obj = ResourceManager.GetObject("face_color_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_0 {
            get {
                object obj = ResourceManager.GetObject("face_shape_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_1 {
            get {
                object obj = ResourceManager.GetObject("face_shape_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_2 {
            get {
                object obj = ResourceManager.GetObject("face_shape_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_3 {
            get {
                object obj = ResourceManager.GetObject("face_shape_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_4 {
            get {
                object obj = ResourceManager.GetObject("face_shape_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_5 {
            get {
                object obj = ResourceManager.GetObject("face_shape_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_6 {
            get {
                object obj = ResourceManager.GetObject("face_shape_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_7 {
            get {
                object obj = ResourceManager.GetObject("face_shape_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap face_shape_8 {
            get {
                object obj = ResourceManager.GetObject("face_shape_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_picture {
            get {
                object obj = ResourceManager.GetObject("folder_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_0 {
            get {
                object obj = ResourceManager.GetObject("glasses_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_1 {
            get {
                object obj = ResourceManager.GetObject("glasses_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_2 {
            get {
                object obj = ResourceManager.GetObject("glasses_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_3 {
            get {
                object obj = ResourceManager.GetObject("glasses_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_4 {
            get {
                object obj = ResourceManager.GetObject("glasses_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_5 {
            get {
                object obj = ResourceManager.GetObject("glasses_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_6 {
            get {
                object obj = ResourceManager.GetObject("glasses_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_7 {
            get {
                object obj = ResourceManager.GetObject("glasses_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_8 {
            get {
                object obj = ResourceManager.GetObject("glasses_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_9 {
            get {
                object obj = ResourceManager.GetObject("glasses_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_A {
            get {
                object obj = ResourceManager.GetObject("glasses_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_B {
            get {
                object obj = ResourceManager.GetObject("glasses_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_C {
            get {
                object obj = ResourceManager.GetObject("glasses_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_D {
            get {
                object obj = ResourceManager.GetObject("glasses_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_E {
            get {
                object obj = ResourceManager.GetObject("glasses_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap glasses_F {
            get {
                object obj = ResourceManager.GetObject("glasses_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_0 {
            get {
                object obj = ResourceManager.GetObject("hair_color_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_1 {
            get {
                object obj = ResourceManager.GetObject("hair_color_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_2 {
            get {
                object obj = ResourceManager.GetObject("hair_color_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_3 {
            get {
                object obj = ResourceManager.GetObject("hair_color_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_4 {
            get {
                object obj = ResourceManager.GetObject("hair_color_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_5 {
            get {
                object obj = ResourceManager.GetObject("hair_color_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_6 {
            get {
                object obj = ResourceManager.GetObject("hair_color_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_7 {
            get {
                object obj = ResourceManager.GetObject("hair_color_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_8 {
            get {
                object obj = ResourceManager.GetObject("hair_color_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_9 {
            get {
                object obj = ResourceManager.GetObject("hair_color_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_A {
            get {
                object obj = ResourceManager.GetObject("hair_color_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_color_B {
            get {
                object obj = ResourceManager.GetObject("hair_color_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_00 {
            get {
                object obj = ResourceManager.GetObject("hair_style_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_01 {
            get {
                object obj = ResourceManager.GetObject("hair_style_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_02 {
            get {
                object obj = ResourceManager.GetObject("hair_style_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_03 {
            get {
                object obj = ResourceManager.GetObject("hair_style_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_04 {
            get {
                object obj = ResourceManager.GetObject("hair_style_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_05 {
            get {
                object obj = ResourceManager.GetObject("hair_style_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_06 {
            get {
                object obj = ResourceManager.GetObject("hair_style_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_07 {
            get {
                object obj = ResourceManager.GetObject("hair_style_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_08 {
            get {
                object obj = ResourceManager.GetObject("hair_style_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_09 {
            get {
                object obj = ResourceManager.GetObject("hair_style_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0A {
            get {
                object obj = ResourceManager.GetObject("hair_style_0A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0B {
            get {
                object obj = ResourceManager.GetObject("hair_style_0B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0C {
            get {
                object obj = ResourceManager.GetObject("hair_style_0C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0D {
            get {
                object obj = ResourceManager.GetObject("hair_style_0D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0E {
            get {
                object obj = ResourceManager.GetObject("hair_style_0E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_0F {
            get {
                object obj = ResourceManager.GetObject("hair_style_0F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_10 {
            get {
                object obj = ResourceManager.GetObject("hair_style_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_11 {
            get {
                object obj = ResourceManager.GetObject("hair_style_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_12 {
            get {
                object obj = ResourceManager.GetObject("hair_style_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_13 {
            get {
                object obj = ResourceManager.GetObject("hair_style_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_14 {
            get {
                object obj = ResourceManager.GetObject("hair_style_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_15 {
            get {
                object obj = ResourceManager.GetObject("hair_style_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hair_style_16 {
            get {
                object obj = ResourceManager.GetObject("hair_style_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_0 {
            get {
                object obj = ResourceManager.GetObject("head_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_1 {
            get {
                object obj = ResourceManager.GetObject("head_0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_2 {
            get {
                object obj = ResourceManager.GetObject("head_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_3 {
            get {
                object obj = ResourceManager.GetObject("head_0_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_4 {
            get {
                object obj = ResourceManager.GetObject("head_0_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_5 {
            get {
                object obj = ResourceManager.GetObject("head_0_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_6 {
            get {
                object obj = ResourceManager.GetObject("head_0_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_7 {
            get {
                object obj = ResourceManager.GetObject("head_0_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_8 {
            get {
                object obj = ResourceManager.GetObject("head_0_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_9 {
            get {
                object obj = ResourceManager.GetObject("head_0_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_0_A {
            get {
                object obj = ResourceManager.GetObject("head_0_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_0 {
            get {
                object obj = ResourceManager.GetObject("head_1_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_1 {
            get {
                object obj = ResourceManager.GetObject("head_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_2 {
            get {
                object obj = ResourceManager.GetObject("head_1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_3 {
            get {
                object obj = ResourceManager.GetObject("head_1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_4 {
            get {
                object obj = ResourceManager.GetObject("head_1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_5 {
            get {
                object obj = ResourceManager.GetObject("head_1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_1_6 {
            get {
                object obj = ResourceManager.GetObject("head_1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_0 {
            get {
                object obj = ResourceManager.GetObject("head_2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_1 {
            get {
                object obj = ResourceManager.GetObject("head_2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_2 {
            get {
                object obj = ResourceManager.GetObject("head_2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_3 {
            get {
                object obj = ResourceManager.GetObject("head_2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_4 {
            get {
                object obj = ResourceManager.GetObject("head_2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap head_2_5 {
            get {
                object obj = ResourceManager.GetObject("head_2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_grid {
            get {
                object obj = ResourceManager.GetObject("ico_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap layout_content {
            get {
                object obj = ResourceManager.GetObject("layout_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_00 {
            get {
                object obj = ResourceManager.GetObject("mouth_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_01 {
            get {
                object obj = ResourceManager.GetObject("mouth_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_02 {
            get {
                object obj = ResourceManager.GetObject("mouth_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_03 {
            get {
                object obj = ResourceManager.GetObject("mouth_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_04 {
            get {
                object obj = ResourceManager.GetObject("mouth_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_05 {
            get {
                object obj = ResourceManager.GetObject("mouth_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_06 {
            get {
                object obj = ResourceManager.GetObject("mouth_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_07 {
            get {
                object obj = ResourceManager.GetObject("mouth_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_08 {
            get {
                object obj = ResourceManager.GetObject("mouth_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_09 {
            get {
                object obj = ResourceManager.GetObject("mouth_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0A {
            get {
                object obj = ResourceManager.GetObject("mouth_0A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0B {
            get {
                object obj = ResourceManager.GetObject("mouth_0B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0C {
            get {
                object obj = ResourceManager.GetObject("mouth_0C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0D {
            get {
                object obj = ResourceManager.GetObject("mouth_0D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0E {
            get {
                object obj = ResourceManager.GetObject("mouth_0E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_0F {
            get {
                object obj = ResourceManager.GetObject("mouth_0F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_10 {
            get {
                object obj = ResourceManager.GetObject("mouth_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_11 {
            get {
                object obj = ResourceManager.GetObject("mouth_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_12 {
            get {
                object obj = ResourceManager.GetObject("mouth_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_13 {
            get {
                object obj = ResourceManager.GetObject("mouth_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_14 {
            get {
                object obj = ResourceManager.GetObject("mouth_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_15 {
            get {
                object obj = ResourceManager.GetObject("mouth_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_16 {
            get {
                object obj = ResourceManager.GetObject("mouth_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_17 {
            get {
                object obj = ResourceManager.GetObject("mouth_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_18 {
            get {
                object obj = ResourceManager.GetObject("mouth_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_19 {
            get {
                object obj = ResourceManager.GetObject("mouth_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1A {
            get {
                object obj = ResourceManager.GetObject("mouth_1A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1B {
            get {
                object obj = ResourceManager.GetObject("mouth_1B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1C {
            get {
                object obj = ResourceManager.GetObject("mouth_1C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1D {
            get {
                object obj = ResourceManager.GetObject("mouth_1D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1E {
            get {
                object obj = ResourceManager.GetObject("mouth_1E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mouth_1F {
            get {
                object obj = ResourceManager.GetObject("mouth_1F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_0 {
            get {
                object obj = ResourceManager.GetObject("nose_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_1 {
            get {
                object obj = ResourceManager.GetObject("nose_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_2 {
            get {
                object obj = ResourceManager.GetObject("nose_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_3 {
            get {
                object obj = ResourceManager.GetObject("nose_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_4 {
            get {
                object obj = ResourceManager.GetObject("nose_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_5 {
            get {
                object obj = ResourceManager.GetObject("nose_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_6 {
            get {
                object obj = ResourceManager.GetObject("nose_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_7 {
            get {
                object obj = ResourceManager.GetObject("nose_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_8 {
            get {
                object obj = ResourceManager.GetObject("nose_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_9 {
            get {
                object obj = ResourceManager.GetObject("nose_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_A {
            get {
                object obj = ResourceManager.GetObject("nose_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_B {
            get {
                object obj = ResourceManager.GetObject("nose_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_C {
            get {
                object obj = ResourceManager.GetObject("nose_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_D {
            get {
                object obj = ResourceManager.GetObject("nose_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_E {
            get {
                object obj = ResourceManager.GetObject("nose_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap nose_F {
            get {
                object obj = ResourceManager.GetObject("nose_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap page_white_copy {
            get {
                object obj = ResourceManager.GetObject("page_white_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap strawberry {
            get {
                object obj = ResourceManager.GetObject("strawberry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
